server:
  port: 8081
  servlet:
    context-path: /employeeapi
    
spring:
  datasource:
    username: root
    password: 12345
    url: jdbc:mysql://localhost:3306/employee?createTableIfNotExists=true
  jpa:     
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
      
eureka:
  instance:
    client:
      serviceUrl:
        defaultZone: http://localhost:8761/eureka/
