server:
  port: 8080
  servlet:
    context-path: /projectapi
    
spring:
  datasource:
      username: root
      password: 12345
      url: jdbc:mysql://localhost:3306/project?createTableIfNotExists=true
  jpa:     
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
  application:
    name: project-service       
    
eureka:
  instance:
    client:
      serviceUrl:
        defaultZone: http://localhost:8761/eureka/
